// This is an autogenerated file from Firebase Studio.

'use server';
import {
  attendanceAnomalyDetection,
  type AttendanceAnomalyDetectionInput,
  type AttendanceAnomalyDetectionOutput,
} from '@/ai/flows/attendance-anomaly-detection';

export async function runAttendanceAnomaly(
  input: AttendanceAnomalyDetectionInput
): Promise<AttendanceAnomalyDetectionOutput> {
  return await attendanceAnomalyDetection(input);
}
