// This is an autogenerated file from Firebase Studio.

'use server';
import {
  analyzeComplianceRisk,
  type ComplianceRiskAnalysisInput,
  type ComplianceRiskAnalysisOutput,
} from '@/ai/flows/compliance-risk-analysis';

export async function runComplianceAnalysis(
  input: ComplianceRiskAnalysisInput
): Promise<ComplianceRiskAnalysisOutput> {
  return await analyzeComplianceRisk(input);
}
